### PR TITLE
Fixing concurrency requests + implementing get_game_status endpoint 

### PR DESCRIPTION
**Pull request by spreadzenox**
Use of quart to allow concurrent requests + implementing of get_game_status.
All tests ok + mergeable

### CODE REVIEW

**Review by Gjovani872 — APPROVED** [review]
Lgtm

**Review by BONSURHA — APPROVED** [review]
all good for me, I updated also the `request.http`

**Review by BONSURHA — CHANGES_REQUESTED** [review]
you have an old version of the frontend main, make sure to integrate the new one

**Comment by BONSURHA** [comment]
as I said before, you're integration is ok, but the main issue is that you branch the main before Thor merge his changes

**Comment by spreadzenox** [comment]
> as I said before, you're integration is ok, but the main issue is that you branch the main before Thor merge his changes

no problem with that it's the principle of merging, i'll keep the changes that are in main just merge my own changes, i'll not erase enything by merging

**Review by BONSURHA — APPROVED** [review]

**Pull request merged**
