### PR TITLE
Percentage of winning

### PR DESCRIPTION
**Pull request by BONSURHA**
percentage of winning connection between `frontend` and `backend`.
A bug related to black mate is now fixed

### CODE REVIEW

**Review by Gjovani872 — APPROVED** [review]
lgtm

**Comment by BONSURHA** [comment]
@thorsjur if you can check the frontend part that @Thalamicks developed

**Comment by thorsjur** [comment]
> @thorsjur if you can check the frontend part that @Thalamicks developed

I reviewed his PR and i think it's merged, does Fede have any code in this PR not contained in his?

**Comment by BONSURHA** [comment]
@Thalamicks added something of the winning percentage also when a user upload a FEN. 
I fixed the upload of a FEN displaying as an error a FEN related to a endgame

**Comment by BONSURHA** [comment]
the last five commits are related to the last changes in the frontend. In this branch we fixed bugs related to our implementation

**Comment by Thalamicks** [comment]
@thorsjur,
The last commits are related to fixing small bugs by changing a few lines of code in specific files:
-  _VictoryBar.jsx_ like lines `12-15, 46, 65:`
- the `fetchProbabilities` in _useChess.js_. 
- the different calls of `fetchProbabilities` in _useChess.js_
The rest is pretty much as before

**Review by thorsjur — APPROVED** [review]
I've checked out the frontend part and it looks good to me

**Pull request merged**
